### ISSUE TITLE
Segmentation fault when enabling game_status true

### ISSUE THREAD

**Issue by runfalk** [bitlbee/bitlbee-steam#126]
I reported my issue in #116, but it turned out to be another traceback for the problem.

Enable `game_status` by running `account steam game_status true` in a control channel. Wait up to one minute before the server crashes. It restarts only to crash again after a short period of time (before showing any friends).

It seems to happen after the response from `https://api.steampowered.com:443/ISteamUserOAuth/GetUserSummaries/v0001`. Skypeweb is also authenticating at the same time.

I have a skypeweb account enabled (I run the libpurple version of bitlbee) and the steam account. I am the only one using bitlbee on my server.

```
Thread 1 "bitlbee" received signal SIGSEGV, Segmentation fault.
0x000055555556bd1b in irc_channel_has_user ()
#0  0x000055555556bd1b in irc_channel_has_user ()
#1  0x00007fffe038d98e in steam_user_chans_msg () from /usr/lib/bitlbee/steam.so
#2  0x00007fffe038766e in ?? () from /usr/lib/bitlbee/steam.so
#3  0x00007fffe03878e0 in ?? () from /usr/lib/bitlbee/steam.so
#4  0x00007fffe038867a in ?? () from /usr/lib/bitlbee/steam.so
#5  0x00007fffe038c0d0 in ?? () from /usr/lib/bitlbee/steam.so
#6  0x00007fffe038c323 in steam_http_req_free () from /usr/lib/bitlbee/steam.so
#7  0x000055555557982f in ?? ()
#8  0x0000555555578624 in ?? ()
#9  0x00007ffff760305a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff7603400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff7603722 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x0000555555563557 in main ()
```

I have saved the entire program output but do not want to publish it here. Can be provided privately upon request.

My current workaround is editing my user.xml file and remove the node for `game_status`.

**Comment by runfalk** [comment]
This is working since I updated to the nightly version. The reason is probably the same as in https://github.com/bitlbee/bitlbee-facebook/issues/142.
