### ISSUE TITLE
Double g_source_remove() when getting 401 from login

### ISSUE THREAD

**Issue by dequis** [bitlbee/bitlbee-steam#127]
```
(process:31292): GLib-CRITICAL **: Source ID 520 was not found when attempting to remove it
```

To reproduce:

```
ac steam set token a
ac steam on
```

```
(gdb) bt full
#0  0x00007ffff76104f0 in g_log () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff760819c in g_source_remove () at /usr/lib/libglib-2.0.so.0
#2  0x00005555555876d7 in b_event_remove (tag=131) at events_glib.c:152
#3  0x00007ffff32a920e in steam_http_req_close (req=0x555555870a60, callback=0) at steam-http.c:287
        __func__ = "steam_http_req_close"
#4  0x00007ffff32a9662 in steam_http_req_done (req=0x555555870a60) at steam-http.c:434
        req = 0x555555870a60
#5  0x0000555555588748 in http_incoming_data (data=0x555555869af0, source=9, cond=B_EV_IO_READ) at http_client.c:304
        req = 0x555555869af0
        buffer = "HTTP/1.1 401 Unauthorized\r\nContent-Length: 174\r\nContent-Type: text/html; charset=UTF-8\r\nExpires: Mon, 27 Feb 2017 20:55:12 GMT\r\nCache-Control: max-age=0, no-cache, no-store\r\nPragma: no-cache\r\nDate: Mon, 27 Feb 2017 20:55:12 GMT\r\nConnection: close\r\n\r\n<html><head><title>Unauthorized</title></head><body><h1>Unauthorized</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>", '\000' <repeats 1576 times>...
        st = 424
#6  0x000055555558753a in gaim_io_invoke (source=0x555555869530, condition=G_IO_IN, data=0x555555812160) at events_glib.c:86
        closure = 0x555555812160
        gaim_cond = B_EV_IO_READ
        st = 21845
#7  0x00007ffff760945a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff7609810 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff7609b32 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#10 0x0000555555587484 in b_main_run () at events_glib.c:59
#11 0x0000555555584c7d in main (argc=2, argv=0x7fffffffe3a8) at unix.c:182
```

**Comment by dgw** [comment]
Does this manifest at all on IRC, or without debug logs turned on? Since my instance was getting a 401 every 15 minutes, like clockwork, for multiple weeks and showed no signs of this. It might be fixed?

**Comment by dequis** [comment]
Usually won't be visible without debug logs. Sometimes appears when using inetd mode.
